// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv dotenv-expand
import * as dotenv from "dotenv";
import { expand } from "dotenv-expand";
import { defineConfig } from "prisma/config";

expand(dotenv.config());

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "nest build && node dist/prisma/seed.js",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
